name: Deadline Notifier

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8:00 AM UTC
  workflow_dispatch:      # Enables manual run from the GitHub Actions tab

jobs:
  deadline-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install  # This ensures node-fetch and other dependencies are installed

      - name: Run Deadline Check Script
        env:
          ORG_ACCESS_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
        run: |
          node .github/scripts/deadline-check-org.mjs


